name: sejafortecorajoso

services:
  server:
    image: hugomods/hugo:exts-non-root
    command: server -D
    volumes:
      - ./:/src
      - ~/hugo_cache:/tmp/hugo_cache
    network_mode: host
    ports:
      - 1313:1313
